alias(
    name = "plugin1",
    actual = "//project/crates-pro/tuplugins/plugin1:plugin1[shared]",
    visibility = ["PUBLIC"],
)

alias(
    name = "plugin2",
    actual = "//project/crates-pro/tuplugins/plugin2:plugin2[shared]",
    visibility = ["PUBLIC"],
)
