//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use crate::db_enums::{CrateType, RepoSyncStatus};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "repo_sync_status")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub crate_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub github_url: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub mega_url: String,
    pub crate_type: CrateType,
    pub status: RepoSyncStatus,
    #[sea_orm(column_type = "Text", nullable)]
    pub err_message: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(column_type = "Text")]
    pub version: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
