//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

pub mod prelude;

pub mod program_dependencies;
pub mod program_versions;
pub mod programs;
pub mod repo_sync_result;
pub mod sea_orm_active_enums;
