//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

pub use super::github_sync_status::Entity as GithubSyncStatus;
pub use super::program_dependencies::Entity as ProgramDependencies;
pub use super::program_versions::Entity as ProgramVersions;
pub use super::programs::Entity as Programs;
pub use super::repo_sync_result::Entity as RepoSyncResult;
