//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "programs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub namespace: String,
    pub max_version: String,
    #[sea_orm(column_type = "Text")]
    pub github_url: String,
    #[sea_orm(column_type = "Text")]
    pub mega_url: String,
    #[sea_orm(column_type = "Text")]
    pub doc_url: String,
    #[sea_orm(column_type = "Text")]
    pub program_type: String,
    pub downloads: i64,
    #[sea_orm(column_type = "Text")]
    pub cratesio: String,
    pub github_analyzed: bool,
    pub repo_created_at: Option<DateTime>,
    pub in_cratesio: bool,
    #[sea_orm(unique)]
    pub github_node_id: String,
    pub updated_at: Option<DateTime>,
    pub repo_sync_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
