//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "programs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub namespace: String,
    pub max_version: String,
    #[sea_orm(column_type = "Text")]
    pub github_url: String,
    #[sea_orm(column_type = "Text")]
    pub mega_url: String,
    #[sea_orm(column_type = "Text")]
    pub doc_url: String,
    #[sea_orm(column_type = "Text")]
    pub program_type: String,
    pub downloads: i64,
    #[sea_orm(column_type = "Text")]
    pub cratesio: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
