[package]
name = "kafka_model"
version = "0.1.0"
edition = "2021"

[dependencies]

entity = { path = "../storage/entity" }

serde = { workspace = true }
chrono = { workspace = true }
sea-orm = { workspace = true }
