[package]
name = "kafka_model"
version = "0.1.0"
edition = "2021"

[dependencies]
entity = { path = "../storage/entity" }

# third-party
chrono = { workspace = true }
sea-orm = { workspace = true }
serde = { workspace = true }
